describe('Audit Log: Admin-only page, action filters, and a fresh entry generated by a real action', () => {
  const uniqueSuffix = Date.now();
  const newUser = {
    firstName: 'AuditFixture',
    lastName: `Test${uniqueSuffix}`,
    email: `audit.fixture${uniqueSuffix}@apollo.com`
  };

  function loginAs(email: string, password: string): void {
    cy.clearCookies();
    localStorage.clear();
    cy.visit('/login');
    cy.get('#email').type(email);
    cy.get('#password').type(password);
    cy.contains('button', 'Sign in').click();
    cy.location('pathname', { timeout: 10000 }).should('eq', '/dashboard');
  }

  it('does not show the Audit Log nav link to a regular Clinician, and the route guard blocks direct navigation', () => {
    loginAs('doctor@apollo.com', 'Test@123');

    cy.contains('a', 'Audit Log').should('not.exist');

    cy.visit('/audit-log');
    cy.location('pathname', { timeout: 10000 }).should('eq', '/dashboard');
  });

  it('lets an Admin create a clinic user, then finds the resulting ClinicUserCreated entry in the audit log via the action filter', () => {
    loginAs('admin@apollo.com', 'Admin@123');

    // Generate a deterministic, fresh audit event.
    cy.contains('a', 'Clinic Management').click();
    cy.location('pathname', { timeout: 10000 }).should('eq', '/clinic-management');
    cy.contains('button', '+ New User').click();
    cy.get('#firstName').type(newUser.firstName);
    cy.get('#lastName').type(newUser.lastName);
    cy.get('#email').type(newUser.email);
    cy.contains('form button', 'Create User').click();
    cy.contains('Temporary password created', { timeout: 10000 }).should('be.visible');

    cy.contains('a', 'Audit Log').click();
    cy.location('pathname', { timeout: 10000 }).should('eq', '/audit-log');
    cy.contains('h1', 'Audit Log').should('be.visible');

    cy.contains('.toggle-option', 'Clinic User Created').click();
    cy.get('tbody tr', { timeout: 10000 }).should('have.length.greaterThan', 0);
    cy.get('tbody tr').first().within(() => {
      cy.contains('Clinic User Created').should('be.visible');
      cy.contains(newUser.email).should('be.visible');
    });
  });

  it('resets to all entries when the "All" filter is selected', () => {
    loginAs('admin@apollo.com', 'Admin@123');

    cy.contains('a', 'Audit Log').click();
    cy.location('pathname', { timeout: 10000 }).should('eq', '/audit-log');

    cy.contains('.toggle-option', 'Patient Created').click();
    cy.get('tbody tr, .state-message', { timeout: 10000 }).should('exist');

    cy.contains('.toggle-option', 'All').click();
    cy.get('tbody tr', { timeout: 10000 }).should('have.length.greaterThan', 0);
    cy.contains('.toggle-option--active', 'All').should('exist');
  });
});
